In [1]:
%matplotlib inline

# Tensors ｜ 張量

張量如同數組和矩陣一樣, 是一種特殊的數據結構。在PyTorch中, 神經網絡的輸入、輸出以及網絡的參數等數據, 都是使用張量來進行描述。

張量的使用和Numpy中的ndarrays很類似, 區別在於張量可以在GPU或其它專用硬件上運行, 這樣可以得到更快的加速效果。


In [2]:
import torch
import numpy as np

# 張量初始化
張量有很多種不同的初始化方法, 先來看看四個簡單的例子：

## 1. 直接生成張量

由原始數據直接生成張量, 張量類型由原始數據類型決定



In [3]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


## 2. 通過Numpy數組來生成張量

由已有的Numpy數組來生成張量



In [4]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)

tensor([[1, 2],
        [3, 4]])


## 3. 通過已有的張量來生成新的張量

新的張量將繼承已有張量的數據屬性(結構、類型), 也可以重新指定新的數據類型。



In [5]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.8847, 0.9140],
        [0.8260, 0.0341]]) 



## 4. 通過指定數據維度來生成張量

shape是元組類型, 用來描述張量的維數, 下面3個函數通過傳入shape來指定生成張量的維數。



In [6]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.0547, 0.1443, 0.6448],
        [0.2473, 0.3092, 0.1391]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


# 張量屬性
從張量屬性我們可以得到張量的維數、數據類型以及它們所存儲的設備(CPU或GPU)。

來看一個簡單的例子:


In [7]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


# 張量運算
有超過100種張量相關的運算操作, 例如轉置、索引、切片、數學運算、線性代數、隨機採樣等。更多的運算可以在這裡查看。

所有這些運算都可以在GPU上運行(相對於CPU來說可以達到更高的運算速度)。


In [8]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
  tensor = tensor.to('cuda')

## 1. 張量的索引和切片



In [9]:
tensor = torch.ones(4, 4)
print('First row: ',tensor[0])
print('First column: ', tensor[:, 0])
print('Last column:', tensor[..., -1])
tensor[:,1] = 0
print(tensor)

First row:  tensor([1., 1., 1., 1.])
First column:  tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


## 2. 張量的拼接

你可以通過torch.cat方法將一組張量按照指定的維度進行拼接, 也可以參考torch.stack方法。這個方法也可以實現拼接操作, 但和torch.cat稍微有點不同。



In [10]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


## 3. 張量的乘積和矩陣乘法




In [11]:
# This computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)


# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

## 單元素張量
如果您有一個單元素張量，例如通過聚合所有
張量的值轉換為一個值，您可以將其轉換為 Python
使用`item()`的數值：



In [12]:
agg = tensor.sum()
agg_item = agg.item()  
print(agg_item, type(agg_item))

12.0 <class 'float'>


## 4. 自動賦值運算

自動賦值運算通常在方法後有 _ 作為後綴, 例如: x.copy_(y), x.t_()操作會改變 x 的取值。



In [13]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


# Tensor與Numpy的轉化
張量和Numpy array數組在CPU上可以共用一塊內存區域, 改變其中一個另一個也會隨之改變。

## 1. 由張量變換為Numpy array數組

In [14]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


修改张量的值，则Numpy array数组值也会随之改变。



In [15]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


## 2. NumPy array to Tensor

In [16]:
n = np.ones(5)
t = torch.from_numpy(n)

修改Numpy array數組的值，則張量值也會隨之改變。





In [17]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
